[CPROD-1016] Move out auction api out of `is20` to `canister-sdk`
infinity-swap/IS20 pull request #105
Opened 2022-07-28 14:31 UTC by awkure

2022-07-29 05:16 UTC, blutooth commented on dfx.json
> +      "wasm": "target/wasm32-unknown-unknown/release/factory.wasm",
I wouldnt change this, likely to break a lot of scripts.

2022-08-17 08:56 UTC, rumatoest requested changes
It is better to rename all fields in structs to snake case, not just some of them.

2022-08-17 08:56 UTC, rumatoest commented on src/token/api/src/canister.rs
>              feeTo: fee_to,
Please fix here other camelCase properties to the snake case in this structure

2022-08-17 08:56 UTC, rumatoest commented on src/token/api/src/canister/erc20_transactions.rs
>                  feeTo: alice(),
snake case please

2022-08-17 15:56 UTC, itsyaasir commented on spec/IS20.md
> +   total_supply : Tokens128; // token total supply
remove this, we don't have `total_supply` in `Metadata`

2022-08-23 08:13 UTC, awkure commented
Oh, this PR is still open

2022-08-24 06:39 UTC, hagsteel requested changes

2022-08-24 06:39 UTC, hagsteel commented on src/token/impl/src/canister.rs
> +            .expect("Someone has the token factory state borrowed.")
```suggestion
            .expect("token factory state already borrowed.")
```

2022-08-24 06:39 UTC, hagsteel commented on src/token/impl/src/canister.rs
> +            .expect("Someone has the token factory state borrowed.")
This applies for all the other ones with the same message.

2022-08-24 07:54 UTC, itsyaasir approved these changes

2022-08-27 20:12 UTC, closed without merging