add no_api propagation
infinity-swap/IS20 pull request #130
Opened 2022-09-13 10:21 UTC by itsyaasir

2022-09-14 07:55 UTC, hagsteel approved these changes

2022-09-19 09:22 UTC, awkure approved these changes

2022-09-19 13:18 UTC, Maximkaaa requested changes

2022-09-19 13:18 UTC, Maximkaaa commented on src/token/impl/Cargo.toml
> +no_api = ["token-api/no_api"]
There's a problem with this change. Take as an example the AMM canister. It depends on both `token-api` and `token-impl` crates. The first dependency is to use token API as is, to allow working with AMM supply as an IS20 token. And the second one is to make inter-canister calls to other IS20 canisters. This means that for AMM api crate should be used without `no_api` feature, and impl crate with it. But if we set the `no_api` on impl crate as suggested in this PR, there would be no way for AMM to turn off `no_api` feature for api create.

2022-09-21 06:36 UTC, closed without merging