Add metrics trait to the factory
infinity-swap/IS20 pull request #136
Opened 2022-09-22 18:45 UTC by Maximkaaa

Marked as draft because the `canister-sdk` tag is temporary. But is ready to be reviewed.

2022-09-23 07:13 UTC, awkure approved these changes

2022-09-26 08:45 UTC, hagsteel requested changes
Generally seems fine but since it has merge conflicts please sort these out and re-request the review

2022-09-29 07:16 UTC, hagsteel approved these changes

2022-09-29 09:46 UTC, itsyaasir approved these changes

2022-09-30 07:44 UTC, merged