[CPROD-1194] Refactor binaries a little
infinity-swap/IS20 pull request #140
Opened 2022-09-28 12:17 UTC by awkure

Just reduces the module definitions in canister binaries

2022-09-29 05:40 UTC, itsyaasir approved these changes

2022-09-29 07:48 UTC, hagsteel requested changes

2022-09-29 07:48 UTC, hagsteel commented on src/factory/src/main.rs
> +    #[cfg(not(target_family = "wasm"))]
I don't think we need this check since we'll never run the `main` function for a canister (correct me if I am wrong)
```suggestion
```

2022-09-29 07:48 UTC, hagsteel commented on src/token/impl/src/main.rs
> +    #[cfg(not(any(target_family = "wasm", test)))]
```suggestion
```

2022-10-04 05:48 UTC, Maximkaaa approved these changes

2022-10-04 09:43 UTC, merged